import { PrismaClient } from "@prisma/client";
import { hashPassword } from "../../utils/hash";

export async function seedUsers(prisma: PrismaClient) {
  const pwHash1 = await hashPassword("Ainur#123");
  const pwHash2 = await hashPassword("Siti#123");
  const pwHash3 = await hashPassword("Budi#123");
  const pwHash4 = await hashPassword("User#123");

  const users = await prisma.user.createMany({
    data: [
      {
        username: "ainur",
        fullname: "Ainur Rofiq",
        email: "ainur@mail.com",
        password: pwHash1,
        bio: "Frontend Developer",
        photo_profile: "http://localhost:3003/public/images/me.jpg",
        cover_photo: "http://localhost:3003/public/images/cover_photo.jpg",
      },
      {
        username: "budi",
        fullname: "Budi Santoso",
        email: "budi@mail.com",
        password: pwHash3,
        bio: "Backend Engineer",
        photo_profile: "http://localhost:3003/public/images/user3.jpg",
      },
      {
        username: "siti",
        fullname: "Siti Aminah",
        email: "siti@mail.com",
        password: pwHash2,
        bio: "UI/UX Designer",
        photo_profile: "http://localhost:3003/public/images/user2.jpg",
      },
      // 20 data tambahan
      {
        username: "dwiputra",
        fullname: "Dwi Putra Pratama",
        email: "dwi.putra@mail.com",
        password: pwHash4,
        bio: "Full Stack Developer | Coffee enthusiast ☕",
        photo_profile: "http://localhost:3003/public/images/user4.jpg",
        cover_photo: "http://localhost:3003/public/images/cover4.jpg",
      },
      {
        username: "rahma_dev",
        fullname: "Rahma Wati",
        email: "rahma.wati@mail.com",
        password: pwHash4,
        bio: "Mobile Developer | React Native | Flutter",
        photo_profile: "http://localhost:3003/public/images/user5.jpg",
      },
      {
        username: "agus_tech",
        fullname: "Agus Setiawan",
        email: "agus.tech@mail.com",
        password: pwHash4,
        bio: "DevOps Engineer | Cloud Architecture",
        photo_profile: "http://localhost:3003/public/images/user6.jpg",
        cover_photo: "http://localhost:3003/public/images/cover6.jpg",
      },
      {
        username: "linda_ui",
        fullname: "Linda Kartika",
        email: "linda.kartika@mail.com",
        password: pwHash4,
        bio: "Product Designer | Making digital products beautiful",
        photo_profile: "http://localhost:3003/public/images/user7.jpg",
      },
      {
        username: "fikri_code",
        fullname: "Fikri Rahman",
        email: "fikri.rahman@mail.com",
        password: pwHash4,
        bio: "Software Engineer @ Tech Startup | Golang lover",
        photo_profile: "http://localhost:3003/public/images/user8.jpg",
        cover_photo: "http://localhost:3003/public/images/cover8.jpg",
      },
      {
        username: "maya_data",
        fullname: "Maya Sari",
        email: "maya.sari@mail.com",
        password: pwHash4,
        bio: "Data Scientist | AI/ML Enthusiast | Python 🐍",
        photo_profile: "http://localhost:3003/public/images/user9.jpg",
      },
      {
        username: "reza_cyber",
        fullname: "Reza Firmansyah",
        email: "reza.cyber@mail.com",
        password: pwHash4,
        bio: "Cybersecurity Specialist | Ethical Hacker",
        photo_profile: "http://localhost:3003/public/images/user10.jpg",
      },
      {
        username: "dina_pm",
        fullname: "Dina Puspita",
        email: "dina.puspita@mail.com",
        password: pwHash4,
        bio: "Product Manager | Tech & Innovation",
        photo_profile: "http://localhost:3003/public/images/user11.jpg",
        cover_photo: "http://localhost:3003/public/images/cover11.jpg",
      },
      {
        username: "hendra_ios",
        fullname: "Hendra Kusuma",
        email: "hendra.ios@mail.com",
        password: pwHash4,
        bio: "iOS Developer | Swift | SwiftUI",
        photo_profile: "http://localhost:3003/public/images/user12.jpg",
      },
      {
        username: "nova_android",
        fullname: "Nova Lestari",
        email: "nova.android@mail.com",
        password: pwHash4,
        bio: "Android Developer | Kotlin enthusiast 🤖",
        photo_profile: "http://localhost:3003/public/images/user13.jpg",
      },
      {
        username: "fajar_cloud",
        fullname: "Fajar Ramadhan",
        email: "fajar.cloud@mail.com",
        password: pwHash4,
        bio: "Cloud Engineer | AWS Certified | Azure",
        photo_profile: "http://localhost:3003/public/images/user14.jpg",
        cover_photo: "http://localhost:3003/public/images/cover14.jpg",
      },
      {
        username: "indah_qa",
        fullname: "Indah Permata",
        email: "indah.qa@mail.com",
        password: pwHash4,
        bio: "QA Engineer | Automation Testing | Selenium",
        photo_profile: "http://localhost:3003/public/images/user15.jpg",
      },
      {
        username: "yoga_blockchain",
        fullname: "Yoga Prasetyo",
        email: "yoga.blockchain@mail.com",
        password: pwHash4,
        bio: "Blockchain Developer | Web3 | Solidity",
        photo_profile: "http://localhost:3003/public/images/user16.jpg",
      },
      {
        username: "putri_ux",
        fullname: "Putri Anggraini",
        email: "putri.ux@mail.com",
        password: pwHash4,
        bio: "UX Researcher | Human-centered design advocate",
        photo_profile: "http://localhost:3003/public/images/user17.jpg",
        cover_photo: "http://localhost:3003/public/images/cover17.jpg",
      },
      {
        username: "arif_database",
        fullname: "Arif Hidayat",
        email: "arif.database@mail.com",
        password: pwHash4,
        bio: "Database Administrator | PostgreSQL | MongoDB",
        photo_profile: "http://localhost:3003/public/images/user18.jpg",
      },
      {
        username: "lina_scrum",
        fullname: "Lina Maharani",
        email: "lina.scrum@mail.com",
        password: pwHash4,
        bio: "Scrum Master | Agile Coach | CSM Certified",
        photo_profile: "http://localhost:3003/public/images/user19.jpg",
      },
      {
        username: "irfan_game",
        fullname: "Irfan Hakim",
        email: "irfan.game@mail.com",
        password: pwHash4,
        bio: "Game Developer | Unity | Unreal Engine",
        photo_profile: "http://localhost:3003/public/images/user20.jpg",
        cover_photo: "http://localhost:3003/public/images/cover20.jpg",
      },
      {
        username: "sarah_content",
        fullname: "Sarah Azzahra",
        email: "sarah.content@mail.com",
        password: pwHash4,
        bio: "Content Creator | Tech Reviewer | Digital Marketing",
        photo_profile: "http://localhost:3003/public/images/user21.jpg",
      },
      {
        username: "andi_network",
        fullname: "Andi Wijaya",
        email: "andi.network@mail.com",
        password: pwHash4,
        bio: "Network Engineer | CCNA | Infrastructure",
        photo_profile: "http://localhost:3003/public/images/user22.jpg",
      },
      {
        username: "dewi_analyst",
        fullname: "Dewi Safitri",
        email: "dewi.analyst@mail.com",
        password: pwHash4,
        bio: "Business Analyst | Data-driven decision maker 📊",
        photo_profile: "http://localhost:3003/public/images/user23.jpg",
        cover_photo: "http://localhost:3003/public/images/cover23.jpg",
      },
    ],
  });

  return users;
}
